[package]
name = "fib-rs"
version = "0.1.0"
edition = "2021"

[lib]
# name = "ffi"
# crate-type = ["dylib"]

crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"

[build-dependencies]
napi-build = "1"
